---
title: "Mitchell"
format: html
---

```{r}
#install.packages("genzplyr") 
# :)

library(ggplot2)
library(tidyverse)
library(polyglotr)
library(genzplyr)
library(gganimate)

data <- iris |>
    glow_up(
        Sepal.Length = 1/Sepal.Length, 
        Petal.Length = log10(Petal.Length), 
        Sepal.Width = Sepal.Width^2, 
        Petal.Width = Petal.Width,
        `team are we locked in :wilted_rose_emoji:` = ifelse(
            Species == "setosa", "сетоза", ifelse(
                Species == "versicolor", "wielokolorowy", ifelse(
                    Species == "virginica", "dziewica", "NA"
                )
                )
        )
    ) |>
    rowwise() |>
    glow_up(`Goodie-Ness` = sample(c(0:2), size = 1), 
           shapeness = sample((0:3), size = 1), 
           sizeness = sample(c(0:10), size = 1)
           ) |>
    vibe_check(-Species)
    
    data$`Goodie-Ness` = factor(data$`Goodie-Ness`, levels = c(0, 1, 2))
    
p <- ggplot(data, aes(x = Sepal.Length, y = Sepal.Width, color = `Goodie-Ness`, size = `team are we locked in :wilted_rose_emoji:`)) + 
    geom_point(shape = data$shapeness) +
    coord_polar() + 
    scale_color_manual(values = c("#93934a", "#4A412A", "#a9000a"), labels = c("bad", "excellent", "satisfatory")) +
    labs(
        x = "Coconuts scored in Reefscape",
        y = "Species"
    ) +
    geom_boxplot(outliers = FALSE, box.linewidth = 0.5, whisker.linewidth = 0.5, staple.linewidth = 0.5) +
    annotate("text", x = 0.15, y = 16, label = "cookage") +
    transition_time(Sepal.Width) + 
    ease_aes('linear')

p
```

```{r}
library(tidyverse)
raw <- read.csv("../shinyapp/data_files/fake_data.csv")
selected = c(449)
data <- raw |>
    filter(team_number %in% selected) |>
    group_by(team_number) |>
    summarize(
        auto_lows = mean(auto_lunites_low) * 4,
        auto_high = mean(auto_lunites_high) * 7,
        auto_missed = mean(auto_lunites_missed),
        tele_highs = mean(pre_high_lunites_scored + post_high_lunites_scored) * 5,
        tele_low = mean(pre_low_lunites_scored + post_low_lunites_scored) * 2,
        tele_missed = mean(pre_lunites_missed + post_lunites_missed),
        tele_passed = mean(pre_lunites_passed + post_lunites_passed),
        move = mean(moved) * 4,
        end = mean(end_position == "linked") * 5
)|>
pivot_longer(cols=c(move, end, auto_lows, auto_high, auto_missed, tele_highs, tele_low, tele_missed, tele_passed), names_to = "type", values_to = "points_score")


ggplot(data, aes(x = factor(team_number), y = points_score, fill = type)) +
       geom_bar(position = "stack", stat = "identity", width = 0.3) +
    labs(title = paste("Level Summary for Team", data$team_number), x = "Team", y = "Score", fill = "Points") + 
    scale_fill_manual(
        values = c(
        "plum1",
        "plum3",
        "plum4",
        "#FFF68F",
        "#FFC156",
        "#3D5A80",
        "#98C1D9",
        "#7DAA92",
        "#003B36"
        ),
        labels = c(
            "auto_lows" = "Auto Low",
            "auto_high" = "Auto High",
            "auto_missed" = "Auto Missed",
            "tele_highs" = "Tele High",
            "tele_low" = "Tele Low",
            "tele_missed" = "Tele Missed",
            "tele_passed" = "Tele Passed",
            "end" = "End",
            "move" = "Move"
        )
            ) +
    theme_bw()
       


```

```{r}
library(scoutR)
library(tidyverse)
raw <- read.csv("../shinyapp/data_files/data.csv")
schedule <- read.csv("../shinyapp/data_files/schedule.csv")
data <- raw |>
    mutate(
        total_score = auto_lunites_high * 7 + auto_lunites_low * 4 + 
                        auto_lunites_missed * 0 + pre_high_lunites_scored * 5 +
                        pre_low_lunites_scored * 2 + pre_lunites_missed * 0 +
                        pre_lunites_passed * 0 + post_high_lunites_scored * 5 +
                        post_low_lunites_scored * 2 + post_lunites_missed * 0 +
                        post_lunites_passed * 0 + moved * 4 + 
                        ifelse(end_position == "linked", 5, 0)
    ) |>
    select(match_number, team_number, total_score) |>
    rowwise() |>
    mutate(
        alliance_color = ifelse(
            (team_number %in% c(schedule[match_number,]$R1, schedule[match_number,]$R2)),
            "red", "blue")
    )

unique_teams <- sort(unique(data$team_number))

lineups <- matrix(0, nrow = max(data$match_number)*2, ncol = length(unique(data$team_number)))
colnames(lineups) <- sort(unique(data$team_number))
for (i in 1:nrow(lineups)) {
    teams <- filter(data, match_number == ceiling(i/2), alliance_color == ifelse(i %% 2, "red", "blue"))
    lineups[i, as.character(teams$team_number)] = 1
}

data <- data |>
    group_by(match_number, alliance_color) |>
    summarize(
        total_score = sum(total_score)
    )

lineups <- as.data.frame(lineups)
lineups$score = data$total_score
w <- rep(1, nrow(lineups))
bunnybots_opr <- lm(score ~ 0 + ., data = lineups, weights = w)$coefficients
a <- sort(bunnybots_opr)
a
```
