---
title: "Nicholas"
format: html
---

Tuesdays

Covered: yes

Section of Shinyapp to do: **Auto Bar Graph**, Sectioned Colored Bar Graph (Scoring Summary), Cycle History

## Single Auto Point Bar Graph

```{r}
library(tidyverse)
raw <- read.csv("../shinyapp/data_files/fake_data.csv")

select<-2106
data <-raw|>
select(auto_lunites_high,team_number,auto_lunites_low,moved)|>
    filter(team_number==select)|>
    group_by(team_number)|>
    summarize(
        ALH=mean(auto_lunites_high)*7,
        ALL=mean(auto_lunites_low)*4,
        move=mean(moved)*4
    ) |>

pivot_longer(cols=c(ALL,ALH,move),
             names_to="type",
             values_to="points")

ggplot(data, aes(x=factor(team_number),y=points, fill=type))+
    geom_bar(position="stack",stat="identity",width=0.3)+
    labs(title=paste("Auto Points for Team",select))
```

## Compare Auto Point Bar Graph

```{r}
library(tidyverse)
raw <- read.csv("../shinyapp/data_files/fake_data.csv")
select<-c(449,6767,422)

data <-raw|>
select(auto_lunites_high,team_number,auto_lunites_low,moved)|>
    filter(team_number==select)|>
    group_by(team_number)|>
    summarize(
        ALH=mean(auto_lunites_high)*7,
        ALL=mean(auto_lunites_low)*4,
        move=mean(moved)*4
    )|>

pivot_longer(cols=c(ALL,ALH,move),
             names_to="type",
             values_to="points")

ggplot(data, aes(x=factor(team_number),y=points, fill=type))+
    geom_bar(position="stack",stat="identity",width=0.3) +
    labs(title=paste("Auto Points for Team",select))
```

## Single Endgame Point Bar Graph

```{r}
library(tidyverse)
raw <- read.csv("../shinyapp/data_files/fake_data.csv")
selected<-449

data <-raw|>
select(bunnies_inside,team_number,end_position)|>
    filter(team_number==selected)
    
data<-data|>
mutate(
        points=case_when(data$end_position == "none" ~ 0, data$end_position == "linked" ~ 5, .default=0)
    )

ggplot(data, aes(x = end_position)) + 
    geom_bar()

data<-data|>
    group_by(team_number)|>
    summarize(
        Bunnies=mean(bunnies_inside)*6,
        End=mean(points),
    )|>

pivot_longer(cols=c(Bunnies,End),
             names_to="type",
             values_to="points")

ggplot(data, aes(x=factor(team_number),y=points, fill=type))+
    geom_bar(position="stack",stat="identity",width=0.3)+
    labs(title=paste("Endgame Points for Team",selected),x="Team Number")+
    theme_bw()

```

```{r}
x=c(1,2,3,4,5,6,7,8,9,10)
y=1:10
raw<-murders|>
    mutate(murder_rate=total/population*10^6)

ggplot(raw,aes(x=total,y=population))+
    geom_point()+
    geom_text(aes(label=abb))
```

```{r}
getwd()
raw<-read.csv("/cloud/project/shinyapp/data_files/fake_data.csv")

select<-449

data<- raw |> filter(team_number==select)|>
    mutate(auto_cycles=auto_lunites_high+auto_lunites_low+auto_lunites_missed
           ,teleop_cycles=pre_high_lunites_scored+pre_low_lunites_scored+pre_lunites_missed+pre_lunites_passed+post_high_lunites_scored+post_low_lunites_scored+post_lunites_missed+post_lunites_passed,
           total_cycles=auto_cycles+teleop_cycles)|>
    select(match_number,auto_cycles,teleop_cycles,total_cycles)

ggplot(data,aes(x=match_number))+
    geom_line(aes(y=auto_cycles,color="red"))+
    geom_line(aes(y=teleop_cycles),color="darkgreen",show.legend = TRUE)+
    geom_line(aes(y=total_cycles),color="black",show.legend = TRUE)+
    labs(x="Match Number", y="Cycles")
```
